from __future__ import annotations

from devflow.control_room.agent_registry import AgentDefinition, adapter_maturity


def builtin_agents() -> dict[str, AgentDefinition]:
    proof_agent = AgentDefinition(
        id="devflow-manual-codex-worker",
        provider="manual",
        model="human-launched-codex",
        adapter="manual",
        adapter_maturity="stable_runtime",
        role="implementation_worker",
        tier="manual",
        default_mode="workspace_write",
        execution_mode="human_launched_agent",
        purpose=(
            "Consume a bounded Dev-Flow task packet, edit only the assigned isolated workspace, "
            "produce structured result/question/failure evidence, then stop. Dev-Flow owns "
            "verification and human-controlled promotion."
        ),
        workspace="isolated_task_workspace",
        can_see=[
            "task_packet",
            "assigned_workspace",
            "recent_events",
            "verification_plan",
            "verification_summary",
        ],
        can_touch=[
            "<workspace>/**",
            "<task>/agents/devflow-manual-codex-worker/result.md",
            "<task>/agents/devflow-manual-codex-worker/questions.jsonl",
            "<task>/agents/devflow-manual-codex-worker/worker_failed.json",
        ],
        cannot_touch=[
            "<main_checkout>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            ".git/**",
        ],
        allowed_reads=[
            "<task>/packet.json",
            "<task>/events.jsonl",
            "<task>/questions.jsonl",
            "<task>/agents/devflow-manual-codex-worker/handoff.md",
            "<workspace>/**",
        ],
        allowed_writes=[
            "<workspace>/**",
            "<task>/agents/devflow-manual-codex-worker/result.md",
            "<task>/agents/devflow-manual-codex-worker/questions.jsonl",
            "<task>/agents/devflow-manual-codex-worker/worker_failed.json",
        ],
        forbidden_writes=[
            "<main_checkout>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            "<task>/packet.json",
            ".git/**",
        ],
        required_outputs=[
            "On completion, write <task>/agents/devflow-manual-codex-worker/result.md with status, summary, changed files, and suggested verification.",
            "When blocked, append one blocked_question JSON object to <task>/agents/devflow-manual-codex-worker/questions.jsonl.",
            "When failed, write <task>/agents/devflow-manual-codex-worker/worker_failed.json with summary, error_type, evidence, and next_safe_action.",
        ],
        completion_rules=[
            "Edit only files under <workspace>.",
            "Never edit the main checkout, .git, <task>/task.yaml, <task>/events.jsonl, <task>/verification.json, or promotion artifacts.",
            "Do not run provider API calls, route models, select models automatically, schedule other agents, verify, promote, commit, or push.",
            "Stop after writing exactly one terminal evidence artifact.",
            "Dev-Flow verification is required after result.md; worker completion is not promotion readiness.",
        ],
        can_run_shell=False,
        can_use_network=False,
        can_promote=False,
        enabled=True,
    )
    shell_agent = AgentDefinition(
        id="devflow-shell-worker",
        provider="shell",
        model="posix-shell",
        adapter="shell",
        adapter_maturity="stable_runtime",
        role="implementation_worker",
        tier="local",
        default_mode="workspace_write",
        execution_mode="automated",
        purpose=(
            "Registry-visible stable shell worker alias. Daily operator use should prefer "
            "`devflow task run <task_id> --worker shell -- <command>`; this alias exists so "
            "agent registry, packet, and runtime contract surfaces can describe the shell lane."
        ),
        workspace="isolated_task_workspace",
        can_see=[
            "task_packet",
            "assigned_workspace",
            "recent_events",
            "verification_plan",
            "verification_summary",
        ],
        can_touch=[
            "<workspace>/**",
            "<task>/agents/devflow-shell-worker/packet.json",
            "<task>/agents/devflow-shell-worker/logs/**",
            "<task>/agents/devflow-shell-worker/result.md",
        ],
        cannot_touch=[
            "<main_checkout>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            ".git/**",
        ],
        allowed_reads=[
            "<task>/packet.json",
            "<task>/events.jsonl",
            "<task>/questions.jsonl",
            "<workspace>/**",
        ],
        allowed_writes=[
            "<workspace>/**",
            "<task>/agents/devflow-shell-worker/packet.json",
            "<task>/agents/devflow-shell-worker/logs/**",
            "<task>/agents/devflow-shell-worker/result.md",
        ],
        forbidden_writes=[
            "<main_checkout>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            ".git/**",
        ],
        required_outputs=[
            "Dev-Flow writes <task>/agents/devflow-shell-worker/packet.json before execution.",
            "Dev-Flow writes <task>/agents/devflow-shell-worker/logs/worker.log from the shell command.",
            "Dev-Flow writes <task>/agents/devflow-shell-worker/result.md with command status and log path.",
        ],
        completion_rules=[
            "Run only the explicit command supplied after `--`.",
            "Mutate only files under <workspace>.",
            "Never edit the main checkout, .git, <task>/task.yaml, <task>/events.jsonl, <task>/verification.json, or promotion artifacts.",
            "Dev-Flow verification is required after result.md; worker completion is not promotion readiness.",
        ],
        can_run_shell=True,
        can_use_network=False,
        can_promote=False,
        enabled=True,
    )
    agents = {proof_agent.id: proof_agent, shell_agent.id: shell_agent}

    # Define standard automated agents mapping to each new execution runtime.
    # Only local Ollama patch agents may execute; remote provider agents stay disabled.
    presets = [
        ("qwopus-implementer", "ollama", "qwopus:latest", "ollama_chat", False, "implementation_worker", "strong_local", "workspace_write", False),
        ("devflow-ollama-worker", "ollama", "qwen2.5-coder:14b", "ollama_chat", False, "implementation_worker", "strong_local", "workspace_write", False),
        ("devflow-openai-worker", "openai", "gpt-4o", "openai_chat", True, "implementation_worker", "strong_local", "workspace_write", False),
        ("devflow-anthropic-worker", "anthropic", "claude-3-5-sonnet", "anthropic_messages", True, "implementation_worker", "strong_local", "workspace_write", False),
        ("devflow-gemini-worker", "gemini", "gemini-1.5-pro", "gemini", True, "implementation_worker", "strong_local", "workspace_write", False),
        ("devflow-openai-compatible-worker", "openai_compatible", "custom-model", "openai_compatible", True, "implementation_worker", "strong_local", "workspace_write", False),
        ("devflow-openai-planner", "openai", "gpt-4o", "openai_chat", True, "frontier_planner_architect_reviewer", "frontier", "frontier_read_only", False),
        ("devflow-openai-reviewer", "openai", "gpt-4o", "openai_chat", True, "frontier_planner_architect_reviewer", "frontier", "frontier_read_only", False),
    ]

    for agent_id, provider, model, adapter, can_use_network, role, tier, default_mode, enabled in presets:
        if default_mode == "workspace_write":
            can_touch = [
                "<workspace>/**",
                f"<task>/agents/{agent_id}/proposal.patch",
                f"<task>/agents/{agent_id}/raw_output.md",
                f"<task>/agents/{agent_id}/result.md",
                f"<task>/agents/{agent_id}/run.json",
                f"<task>/agents/{agent_id}/logs/**",
                f"<task>/agents/{agent_id}/questions.jsonl",
                f"<task>/agents/{agent_id}/worker_failed.json",
            ]
            allowed_writes = [
                "<workspace>/**",
                f"<task>/agents/{agent_id}/proposal.patch",
                f"<task>/agents/{agent_id}/raw_output.md",
                f"<task>/agents/{agent_id}/result.md",
                f"<task>/agents/{agent_id}/run.json",
                f"<task>/agents/{agent_id}/logs/**",
                f"<task>/agents/{agent_id}/questions.jsonl",
                f"<task>/agents/{agent_id}/worker_failed.json",
            ]
            forbidden_writes = [
                "<main_checkout>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                "<task>/packet.json",
                ".git/**",
            ]
            comp_rules = [
                "Edit only files under <workspace>.",
                "Never edit the main checkout, .git, <task>/task.yaml, <task>/events.jsonl, <task>/verification.json, or promotion artifacts.",
                "Stop after writing exactly one terminal evidence artifact.",
                "Dev-Flow verification is required after result.md; worker completion is not promotion readiness.",
            ]
        else:
            can_touch = [
                f"<task>/agents/{agent_id}/result.md",
                f"<task>/agents/{agent_id}/questions.jsonl",
                f"<task>/agents/{agent_id}/worker_failed.json",
            ]
            allowed_writes = [
                f"<task>/agents/{agent_id}/result.md",
                f"<task>/agents/{agent_id}/questions.jsonl",
                f"<task>/agents/{agent_id}/worker_failed.json",
            ]
            forbidden_writes = [
                "<main_checkout>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                "<task>/packet.json",
                ".git/**",
                "<workspace>/**",
            ]
            comp_rules = [
                "Do not edit files in the workspace.",
                "Never edit the main checkout, .git, <task>/task.yaml, <task>/events.jsonl, <task>/verification.json, or promotion artifacts.",
                "Stop after writing exactly one terminal evidence artifact.",
                "Dev-Flow verification is required after result.md; worker completion is not promotion readiness.",
            ]

        agents[agent_id] = AgentDefinition(
            id=agent_id,
            provider=provider,
            model=model,
            adapter=adapter,
            adapter_maturity=adapter_maturity(adapter),
            role=role,
            tier=tier,
            default_mode=default_mode,
            execution_mode="automated",
            purpose=f"Automated execution worker that drives {role} tasks using the {provider} provider.",
            workspace="isolated_task_workspace",
            can_see=[
                "task_packet",
                "assigned_workspace",
                "recent_events",
                "verification_plan",
                "verification_summary",
            ],
            can_touch=can_touch,
            cannot_touch=[
                "<main_checkout>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                ".git/**",
            ],
            allowed_reads=[
                "<task>/packet.json",
                "<task>/events.jsonl",
                "<task>/questions.jsonl",
                f"<task>/agents/{agent_id}/handoff.md",
                "<workspace>/**",
            ],
            allowed_writes=allowed_writes,
            forbidden_writes=forbidden_writes,
            required_outputs=[
                f"On completion, write <task>/agents/{agent_id}/result.md with status, summary, changed files, and suggested verification.",
                f"When blocked, append one blocked_question JSON object to <task>/agents/{agent_id}/questions.jsonl.",
                f"When failed, write <task>/agents/{agent_id}/worker_failed.json with summary, error_type, evidence, and next_safe_action.",
            ],
            completion_rules=comp_rules,
            can_run_shell=False,
            can_use_network=can_use_network,
            can_promote=False,
            enabled=enabled,
        )

    starter_local_profiles = [
        {
            "id": "local-gemma4-qat",
            "model": "gemma4:12b-it-qat",
            "role": "local_senior_worker",
            "tier": "strong_local",
            "model_role_name": "local-gemma4-qat",
            "machine_class": "either",
            "weight_class": "medium",
            "secondary_roles": ["long-context-reviewer", "vision-reviewer", "evidence-brief-writer"],
            "purpose": "Long-context local Gemma 4 QAT evidence profile for bounded review, planning, and vision-adjacent checks.",
            "use_caution": ["Advisory evidence only; keep worker execution, verification, promotion, commit, merge, and push under Dev-Flow gates."],
            "required_verification_command": "ollama show gemma4:12b-it-qat",
            "manifest_notes": ["Local Gemma 4 12B QAT profile with long context; verify actual manifest on the current machine before high-trust use."],
            "hermes_delegable": False,
            "reliable_context_tokens": 249036,
            "vision": True,
            "thinking": True,
            "code_focus": "general_purpose",
            "speed_class": "medium",
            "architecture_class": "dense",
            "fim_support": False,
            "input_modalities": ["text", "image", "screenshot"],
            "tool_access": ["devflow-context"],
            "tuned_for_archetypes": ["ui_visual_review", "context_synthesis", "documentation", "architecture_design"],
        },
        {
            "id": "local-qwen25-coder-14b",
            "model": "qwen2.5-coder:14b",
            "role": "implementation_worker",
            "tier": "strong_local",
            "model_role_name": "local-qwen25-coder-14b",
            "machine_class": "either",
            "weight_class": "medium",
            "secondary_roles": ["code-reviewer", "test-planner", "fallback-coder"],
            "purpose": "Installed local code-tuned fallback for bounded review, test planning, and implementation evidence.",
            "use_caution": ["Advisory evidence only; do not write proposal.patch or mutate the workspace from this read-only worker-pool profile."],
            "required_verification_command": "ollama show qwen2.5-coder:14b",
            "manifest_notes": ["Strongest retained installed Qwen coder fallback in the simplified local profile set."],
            "hermes_delegable": False,
            "reliable_context_tokens": 32768,
            "vision": False,
            "thinking": False,
            "code_focus": "code_specialist",
            "speed_class": "medium",
            "architecture_class": "dense",
            "fim_support": False,
            "input_modalities": ["text"],
            "tool_access": ["devflow-context"],
            "tuned_for_archetypes": ["trivial_edit", "code_review", "documentation"],
        },
    ]

    for profile in starter_local_profiles:
        agents[str(profile["id"])] = AgentDefinition(
            id=profile["id"],
            provider="ollama",
            model=profile["model"],
            adapter="ollama_chat",
            adapter_maturity=adapter_maturity("ollama_chat"),
            role=profile["role"],
            tier=profile["tier"],
            default_mode="read_only",
            execution_mode="automated",
            purpose=profile["purpose"],
            model_role_name=profile["model_role_name"],
            machine_class=profile["machine_class"],
            weight_class=profile["weight_class"],
            secondary_roles=profile["secondary_roles"],
            use_caution=profile["use_caution"],
            required_verification_command=profile["required_verification_command"],
            model_alias_group=profile.get("model_alias_group"),
            manifest_notes=profile["manifest_notes"],
            workspace="isolated_task_workspace",
            can_see=[
                "task_packet",
                "assigned_workspace",
                "recent_events",
                "verification_plan",
                "verification_summary",
            ],
            can_touch=[
                "<task>/local-model-runs/**",
            ],
            cannot_touch=[
                "<main_checkout>/**",
                "<workspace>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                "<task>/agents/**/proposal.patch",
                ".git/**",
            ],
            allowed_reads=[
                "<task>/packet.json",
                "<task>/events.jsonl",
                "<task>/questions.jsonl",
                "<workspace>/**",
            ],
            allowed_writes=[
                "<task>/local-model-runs/**",
            ],
            forbidden_writes=[
                "<main_checkout>/**",
                "<workspace>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                "<task>/packet.json",
                "<task>/agents/**/proposal.patch",
                ".git/**",
            ],
            required_outputs=[
                "Write bounded WorkerEvidence only under <task>/local-model-runs/<run-id>/.",
                "Preserve capped raw output, response text, packet text, and run metadata.",
                "Treat any quality score or routing hint as advisory evidence only.",
            ],
            completion_rules=[
                "Do not edit source files or the assigned workspace.",
                "Do not write proposal.patch, apply patches, verify, commit, merge, push, promote, or mutate task canonical state.",
                "Use the local model endpoint only through Dev-Flow's configured local model client boundary.",
                "Worker output is evidence, not truth; human approval controls promotion.",
            ],
            can_run_shell=False,
            can_use_network=False,
            can_promote=False,
            hermes_delegable=bool(profile["hermes_delegable"]),
            reliable_context_tokens=profile.get("reliable_context_tokens"),
            vision=profile.get("vision"),
            thinking=profile.get("thinking"),
            code_focus=profile.get("code_focus"),
            speed_class=profile.get("speed_class"),
            architecture_class=profile.get("architecture_class"),
            fim_support=profile.get("fim_support"),
            input_modalities=list(profile.get("input_modalities", [])),
            tool_access=list(profile.get("tool_access", [])),
            tuned_for_archetypes=list(profile.get("tuned_for_archetypes", [])),
            enabled=True,
        )

    agents["local-qwen35-mtp"] = AgentDefinition(
        id="local-qwen35-mtp",
        provider="qwen35-mtp",
        model="qwen35-9b-mtp",
        adapter="openai_compatible",
        adapter_maturity=adapter_maturity("openai_compatible"),
        role="frontier_planner_architect_reviewer",
        tier="frontier",
        default_mode="frontier_read_only",
        execution_mode="automated",
        purpose="Fast local OpenAI-compatible advisory profile for status, planning, Telegram, and operator-control loops.",
        model_role_name="local-qwen35-mtp",
        secondary_roles=["status", "planning", "telegram", "operator-control", "advisory"],
        use_caution=[
            "Advisory evidence only; do not create tasks, run workers, apply patches, verify, promote, commit, merge, or push."
        ],
        required_verification_command=None,
        manifest_notes=["Local qwen35-mtp endpoint must be confirmed via /v1/models before high-trust use."],
        reliable_context_tokens=65536,
        vision=False,
        thinking=True,
        code_focus="general_purpose",
        speed_class="fast",
        architecture_class="moe",
        fim_support=False,
        input_modalities=["text"],
        tool_access=["devflow-context", "telegram"],
        tuned_for_archetypes=["status", "planning", "brainstorm", "operator_control"],
        workspace="isolated_task_workspace",
        can_see=["supervisor_packet", "task_packet", "status_projection", "verification_ledger_summary"],
        can_touch=["<task>/agent-advisory-runs/**"],
        cannot_touch=[
            "<main_checkout>/**",
            "<workspace>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            "<task>/agents/**/proposal.patch",
            ".git/**",
        ],
        allowed_reads=[
            "<task>/packet.json",
            "<task>/events.jsonl",
            "<task>/questions.jsonl",
            "<workspace>/**",
            "<repo>/docs/verification-ledger.md",
        ],
        allowed_writes=["<reports>/agent-advisory-runs/**", "<task>/agent-advisory-runs/**"],
        forbidden_writes=[
            "<main_checkout>/**",
            "<workspace>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            "<task>/packet.json",
            "<task>/agents/**/proposal.patch",
            ".git/**",
        ],
        required_outputs=[
            "Write advisory prompt, response, run metadata, usage when returned, recommendations, and safety flags under agent-advisory-runs.",
            "Treat all recommendations as evidence only; Dev-Flow and the human operator own task creation, worker execution, verification, promotion, commit, merge, and push.",
        ],
        completion_rules=[
            "Use bounded Dev-Flow state only; do not scan the full repository blindly.",
            "Do not create tasks, run workers, apply patches, verify, promote, commit, push, or mutate canonical state.",
            "Return one highest-impact next safe action grounded in the supplied evidence.",
        ],
        can_run_shell=False,
        can_use_network=False,
        can_promote=False,
        hermes_delegable=False,
        enabled=True,
    )

    remote_advisory_profiles = [
        {
            "id": "hermes-sonnet46",
            "model": "anthropic/claude-sonnet-4.6",
            "role": "frontier_planner_architect_reviewer",
            "tier": "frontier",
            "default_mode": "frontier_read_only",
            "purpose": "Balanced paid OpenRouter advisory profile for daily coding review, implementation planning, and worker-output critique.",
            "model_role_name": "Hermes Sonnet 4.6",
            "secondary_roles": ["review", "implementation-planning", "daily-paid", "advisory"],
            "use_caution": [
                "Advisory evidence only; do not create tasks, run workers, apply patches, verify, promote, commit, or push."
            ],
            "hermes_delegable": False,
            "vision": True,
            "thinking": True,
            "code_focus": "frontier_general",
            "speed_class": "medium",
            "input_modalities": ["text", "image", "screenshot"],
            "tool_access": ["devflow-context", "browser-context-when-supplied"],
            "tuned_for_archetypes": ["browser_ui_review", "ui_visual_review", "code_review", "implementation_planning"],
        },
        {
            "id": "hermes-opus48",
            "model": "anthropic/claude-opus-4.8",
            "role": "frontier_planner_architect_reviewer",
            "tier": "frontier",
            "default_mode": "frontier_read_only",
            "purpose": "Deep paid OpenRouter advisory profile for hardest architecture, design, and judgment passes.",
            "model_role_name": "Hermes Opus 4.8",
            "secondary_roles": ["architecture-review", "judge", "deep-review", "hardest-design"],
            "use_caution": [
                "Use by explicit profile/job selection for high-value judgment; advisory evidence only."
            ],
            "hermes_delegable": False,
            "vision": True,
            "thinking": True,
            "code_focus": "frontier_general",
            "speed_class": "slow",
            "input_modalities": ["text", "image", "screenshot"],
            "tool_access": ["devflow-context", "browser-context-when-supplied"],
            "tuned_for_archetypes": ["architecture_design", "deep_debugging", "ui_visual_review", "judge"],
        },
        {
            "id": "hermes-qwen37max",
            "model": "qwen/qwen3.7-max",
            "role": "frontier_planner_architect_reviewer",
            "tier": "frontier",
            "default_mode": "frontier_read_only",
            "purpose": "Strong Qwen max paid advisory profile for high-depth coding, reasoning, and alternative review.",
            "model_role_name": "Hermes Qwen 3.7 Max",
            "secondary_roles": ["high-depth-coding", "reasoning", "review", "advisory"],
            "use_caution": [
                "Advisory evidence only; do not create tasks, run workers, apply patches, verify, promote, commit, or push."
            ],
            "hermes_delegable": False,
            "vision": False,
            "thinking": True,
            "code_focus": "frontier_coder",
            "speed_class": "medium",
            "input_modalities": ["text"],
            "tool_access": ["devflow-context"],
            "tuned_for_archetypes": ["complex_implementation", "code_review", "architecture_design", "deep_debugging"],
        },
        {
            "id": "hermes-qwen37plus",
            "model": "qwen/qwen3.7-plus",
            "role": "frontier_planner_architect_reviewer",
            "tier": "frontier",
            "default_mode": "frontier_read_only",
            "purpose": "Efficient Qwen Plus paid advisory profile for default planning, brainstorming, and operator-friendly synthesis.",
            "model_role_name": "Hermes Qwen 3.7 Plus",
            "secondary_roles": ["brainstorm", "planning", "spec-intake", "advisory"],
            "use_caution": [
                "Advisory evidence only; do not create tasks, run workers, apply patches, verify, promote, commit, or push."
            ],
            "hermes_delegable": False,
            "vision": False,
            "thinking": True,
            "code_focus": "frontier_general",
            "speed_class": "fast",
            "input_modalities": ["text"],
            "tool_access": ["devflow-context"],
            "tuned_for_archetypes": ["brainstorm", "planning", "documentation", "context_synthesis"],
            "allowed_reads": [
                "<repo>/docs/verification-ledger.md",
                "<brainstorms>/**",
            ],
            "allowed_writes": [
                "<brainstorms>/**",
            ],
        },
        {
            "id": "hermes-minimaxm3",
            "model": "minimax/minimax-m3",
            "role": "frontier_planner_architect_reviewer",
            "tier": "frontier",
            "default_mode": "frontier_read_only",
            "purpose": "Alternative paid OpenRouter advisory profile for second-opinion implementation, review, and coding evidence.",
            "model_role_name": "Hermes MiniMax M3",
            "secondary_roles": ["second-opinion", "implementation-review", "coding", "advisory"],
            "use_caution": [
                "Advisory evidence only; do not create tasks, run workers, apply patches, verify, promote, commit, or push."
            ],
            "hermes_delegable": False,
            "vision": False,
            "thinking": True,
            "code_focus": "frontier_coder",
            "speed_class": "medium",
            "input_modalities": ["text"],
            "tool_access": ["devflow-context"],
            "tuned_for_archetypes": ["complex_implementation", "code_review", "second_opinion", "deep_debugging"],
        },
    ]

    for profile in remote_advisory_profiles:
        agent_id = str(profile["id"])
        agents[agent_id] = AgentDefinition(
            id=agent_id,
            provider="openrouter",
            model=str(profile["model"]),
            adapter="openai_compatible",
            adapter_maturity=adapter_maturity("openai_compatible"),
            role=str(profile["role"]),
            tier=str(profile["tier"]),
            default_mode=profile["default_mode"],
            execution_mode="automated",
            purpose=str(profile["purpose"]),
            model_role_name=str(profile["model_role_name"]),
            secondary_roles=list(profile["secondary_roles"]),
            use_caution=list(profile["use_caution"]),
            required_verification_command=None,
            manifest_notes=["Model slug must be validated against OpenRouter at runtime before relying on it."],
            workspace="isolated_task_workspace",
            can_see=[
                "supervisor_packet",
                "task_packet",
                "status_projection",
                "verification_ledger_summary",
            ],
            can_touch=[
                "<task>/agent-advisory-runs/**",
            ],
            cannot_touch=[
                "<main_checkout>/**",
                "<workspace>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                "<task>/agents/**/proposal.patch",
                ".git/**",
            ],
            allowed_reads=[
                "<task>/packet.json",
                "<task>/events.jsonl",
                "<task>/questions.jsonl",
                "<workspace>/**",
                "<repo>/docs/verification-ledger.md",
            ]
            if "allowed_reads" not in profile
            else list(profile["allowed_reads"]),
            allowed_writes=[
                "<reports>/agent-advisory-runs/**",
                "<task>/agent-advisory-runs/**",
            ]
            if "allowed_writes" not in profile
            else list(profile["allowed_writes"]),
            forbidden_writes=[
                "<main_checkout>/**",
                "<workspace>/**",
                "<task>/task.yaml",
                "<task>/events.jsonl",
                "<task>/verification.json",
                "<task>/merge-readiness.json",
                "<task>/packet.json",
                "<task>/agents/**/proposal.patch",
                ".git/**",
            ],
            required_outputs=[
                "Write advisory prompt, response, run metadata, usage when returned, recommendations, and safety flags under agent-advisory-runs.",
                "Treat all recommendations as evidence only; Dev-Flow and the human operator own task creation, worker execution, verification, promotion, commit, and push.",
            ],
            completion_rules=[
                "Use bounded Dev-Flow state only; do not scan the full repository blindly.",
                "Do not create tasks, run workers, apply patches, verify, promote, commit, push, or mutate canonical state.",
                "Return one highest-impact next safe action grounded in the supplied evidence.",
            ],
            can_run_shell=False,
            can_use_network=False,
            can_promote=False,
            hermes_delegable=bool(profile["hermes_delegable"]),
            reliable_context_tokens=profile.get("reliable_context_tokens"),
            vision=profile.get("vision"),
            thinking=profile.get("thinking"),
            code_focus=profile.get("code_focus"),
            speed_class=profile.get("speed_class"),
            architecture_class=profile.get("architecture_class"),
            fim_support=profile.get("fim_support"),
            input_modalities=list(profile.get("input_modalities", [])),
            tool_access=list(profile.get("tool_access", [])),
            tuned_for_archetypes=list(profile.get("tuned_for_archetypes", [])),
            enabled=True,
        )

    agents["hermes-codex-gpt55"] = AgentDefinition(
        id="hermes-codex-gpt55",
        provider="openai-codex",
        model="gpt-5.5",
        adapter="hermes_profile",
        adapter_maturity=adapter_maturity("hermes_profile"),
        role="frontier_planner_architect_reviewer",
        tier="frontier",
        default_mode="frontier_read_only",
        execution_mode="automated",
        purpose=(
            "Human-selected Hermes Codex GPT 5.5 advisory profile for Brainstorm, "
            "Builder, and Judge model pickers."
        ),
        model_role_name="Hermes Codex GPT 5.5",
        secondary_roles=["brainstorm", "builder", "judge", "codex", "architecture-review"],
        use_caution=[
            "Hermes/OpenAI subscription profile only; do not route through OpenRouter or provider API keys.",
            "Advisory evidence only; do not create tasks, run workers, apply patches, verify, promote, commit, or push.",
        ],
        manifest_notes=[
            "Uses the Hermes openai-codex subscription profile instead of OpenRouter billing.",
            "Direct Dev-Flow provider execution is intentionally disabled until a Hermes runtime adapter is implemented.",
        ],
        vision=None,
        thinking=True,
        code_focus="frontier_coder",
        speed_class="medium",
        input_modalities=["text", "browser-context-when-supplied", "screenshot-context"],
        tool_access=["hermes-cli", "devflow", "browser-context-when-supplied"],
        tuned_for_archetypes=[
            "complex_implementation",
            "browser_ui_review",
            "code_review",
            "architecture_design",
            "judge",
        ],
        workspace="isolated_task_workspace",
        can_see=[
            "supervisor_packet",
            "task_packet",
            "status_projection",
            "verification_ledger_summary",
        ],
        can_touch=[
            "<brainstorms>/**",
        ],
        cannot_touch=[
            "<main_checkout>/**",
            "<workspace>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            "<task>/agents/**/proposal.patch",
            ".git/**",
        ],
        allowed_reads=[
            "<repo>/docs/verification-ledger.md",
            "<brainstorms>/**",
        ],
        allowed_writes=[
            "<brainstorms>/**",
        ],
        forbidden_writes=[
            "<main_checkout>/**",
            "<workspace>/**",
            "<task>/task.yaml",
            "<task>/events.jsonl",
            "<task>/verification.json",
            "<task>/merge-readiness.json",
            "<task>/packet.json",
            "<task>/agents/**/proposal.patch",
            ".git/**",
        ],
        required_outputs=[
            "Record advisory prompt, response, model identity, and subscription-profile handoff metadata under brainstorm evidence.",
            "Treat all recommendations as evidence only; Dev-Flow and the human operator own task creation, worker execution, verification, promotion, commit, and push.",
        ],
        completion_rules=[
            "Use bounded Dev-Flow state only; do not scan the full repository blindly.",
            "Do not create tasks, run workers, apply patches, verify, promote, commit, push, or mutate canonical state.",
            "Do not route this profile through OpenRouter or OPENROUTER_API_KEY.",
        ],
        can_run_shell=False,
        can_use_network=False,
        can_promote=False,
        hermes_delegable=False,
        enabled=True,
    )

    return agents
